---
key_type: genrsa
key_size: 1024
random_files:
- /home/downloads
key_file: certs/server.pem
csr_file: certs/csr_server.pem
cert_descriptions:
  O: Osaka University
  OU: Cybermedia Center
  CN: server.osaka-u.ac.jp
